FORMAT: 1A
HOST: http://orders.apiblueprint.org/

# Joint orders

## Data Structures

### Supplier
+ id: 1 (number)
+ name: Шаурма на Средном
+ description: Best shaurma in NN!
+ address: `Костина, 13par
+ phone_numbers: `+7-910-895-01-66`, `+7(831)433-05-64` (array[string])
+ rating: 4.75 (number)

### MenuItem
+ id: 1 (number)
+ name: Шаурма со свининой стандартная
+ base_price: 140 (number)

### MenuItemOption
+ id: 1 (number)
+ name: без лука
+ price: 0 (number)

### OrderStatus (enum)
- GATHERING (string)
- LOCKED (string)
- ORDERED (string)
- COMPLETED (string)

### Order
+ id: 1 (number)
+ status: GATHERING (OrderStatus) - Possible values
+ estimated_delivery: 1491052727 (number)
+ owner_id: 1 (number)
+ supplier_id: 1 (number)

### OrderItem
+ id: 1 (number)
+ menu_item_id: 1 (number) - menu item id
+ options: [1, 2, 3] (array[number])  - list of item options

### UserRole (enum)
- ADMIN (string)
- ORGANIZER (string)
- EATER (string)

### User
+ id: 1 (number)
+ username: ekropotin (string) - user's login
+ full_name: Eugene (string) - user's name
+ email: testemail@gmail.com (string)
+ phone_number +71111111111 (string)
+ role: EATER (UserRole)

## Suppliers collection [/suppliers]

### List All Suppliers [GET]

+ Response 200 (application/json)
    + Attributes (array[Supplier])

### Create a New Supplier [POST]

+ Request (application/json)
    + Attributes
        + name: Шаурма на Средном (required)
        + description: Best shaurma in NN!
        + address: `Костина, 13`
        + phone_numbers: `+7-910-895-01-66`, `+7(831)433-05-64` (required, array[string])
        + rating: 4.75 (number)

+ Response 201 (application/json)
    + Headers

            Location: /suppliers/1

    + Attributes (Supplier)

### Get a supplier [GET /suppliers/{id}]
+ Parameters
    + id: 1 (number) supplier's id

+ Response 200 (application/json)
    + Attributes (Supplier)

### Update a Supplier [PUT /suppliers/{id}]
+ Parameters
    + id: 1 (number) supplier's id

+ Request (application/json)
    + Attributes
        + name: Шаурма на Средном
        + description: Best shaurma in NN!
        + address: `Костина, 13`
        + phone_numbers: `+7-910-895-01-66`, `+7(831)433-05-64` (array[string])
        + rating: 4.75 (number)

+ Response 200 (application/json)
    + Attributes (Supplier)

### Delete a Supplier [DELETE /suppliers/{id}]
+ Parameters
    + id: 1 (number) supplier's id

+ Response 204

## Menu collection [/suppliers/{id}/menu_items]
+ Parameters
    + id: 1 (number) supplier id

### List All Menu [GET]

+ Response 200 (application/json)
    + Attributes (array[MenuItem])

### Create a new menu item [POST]

+ Request (application/json)
    + Attributes
        + name: Шаурма со свининой стандартная (required)
        + base_price: 140 (required, number)

+ Response 201 (application/json)
    + Headers

            Location: /suppliers/1/menu_items/1

    + Attributes (MenuItem)

### Get a menu item [GET /suppliers/{supplier_id}/menu_items/{menu_item_id}]
+ Parameters
    + supplier_id: 1 (number) supplier id
    + menu_item_id: 1 (number) menu item id

+ Response 200 (application/json)
    + Attributes (MenuItem)

### Update a menu item [PUT /suppliers/{supplier_id}/menu_items/{menu_item_id}]
+ Parameters
    + supplier_id: 1 (number) supplier id
    + menu_item_id: 1 (number) menu item id

+ Request (application/json)
    + Attributes
        + name: Шаурма со свининой стандартная
        + base_price: 140 (number)

+ Response 200 (application/json)
    + Attributes (MenuItem)

### Delete a menu item [DELETE /suppliers/{supplier_id}/menu_items/{menu_item_id}]
+ Parameters
    + supplier_id: 1 (number) supplier id
    + menu_item_id: 1 (number) menu item id

+ Response 204

## Menu options collection [/suppliers/{supplier_id}/menu_items/{menu_item_id}/options]
+ Parameters
    + supplier_id: 1 (number) supplier id
    + menu_item_id: 1 (number) menu item id

### List All Menu options[GET]

+ Response 200 (application/json)
    + Attributes (array[MenuItemOption])

### Create a new menu item [POST]

+ Request (application/json)
    + Attributes
        + name: Без лука (required)
        + price: 0 (required, number)

+ Response 201 (application/json)
    + Headers

            Location: /suppliers/1/menu_items/1/options/1

    + Attributes (MenuItemOption)

### Update a menu item [PUT /suppliers/{supplier_id}/menu_items/{menu_item_id}/options/{menu_option_id}]
+ Parameters
    + supplier_id: 1 (number) supplier id
    + menu_item_id: 1 (number) menu item id
    + menu_option_id: 1 (number) menu option id

+ Request (application/json)
    + Attributes
        + name: Без лука
        + price: 0 (number)

+ Response 200 (application/json)
    + Attributes (MenuItemOption)

### Delete a menu item [DELETE /suppliers/{supplier_id}/menu_items/{menu_item_id}/options/{menu_option_id}]
+ Parameters
    + supplier_id: 1 (number) supplier id
    + menu_item_id: 1 (number) menu item id
    + menu_option_id: 1 (number) menu option id

+ Response 204

## Orders collection [/orders]

### List All Orders [GET]

+ Response 200 (application/json)
    + Attributes (array[Order])

### Create a new Order [POST]

+ Request (application/json)
    + Attributes (Order)

+ Response 201 (application/json)
    + Headers

            Location: /orders/1

    + Attributes (Order)

### Get an order [GET /orders/{id}]
+ Parameters
    + id: 1 (number) order's id

+ Response 200 (application/json)
    + Attributes (Order)

### Update an Order [PUT /orders/{id}]
+ Parameters
    + id: 1 (number) order's id

+ Request (application/json)
    + Attributes (Order)

+ Response 200 (application/json)
    + Attributes (Order)

### Delete an Order [DELETE /orders/{id}]
+ Parameters
    + id: 1 (number) order's id

+ Response 204

## Order's participants collection [/orders/{id}/participants]
+ Parameters
    + id: 1 (number) order id

### List All participants [GET]

+ Response 200 (application/json)
    + Attributes (array[number])

### Add user to the order [POST]

+ Request (application/json)
    + Attributes (number)

+ Response 201 (application/json)
    + Headers

            Location: /orders/1/participants/1

    + Attributes (array[number])

### Remove user from the order [DELETE /orders/{order_id}/participants/{participant_id}]
+ Parameters
    + order_id: 1 (number) order's id
    + participant_id: 1 (number) user id

+ Response 204
    + Attributes (array[number])

## Order items collection [/orders/{order_id}/participants/{participant_id}]
+ Parameters
    + order_id: 1 (number) order's id
    + participant_id: 1 (number) user id

### Get an order of the participant [GET]

+ Response 200 (application/json)
    + Attributes (array[OrderItem])

### Add menu item in the order [POST]

+ Request (application/json)
    + Attributes
        + menu_item_id: 1 (required, number)
        + options: [1, 2, 3] (required, array[number])

+ Response 201 (application/json)
    + Headers

            Location: /orders/1/participants/1

    + Attributes (MenuItem)

### Update an options for order item [PUT /orders/{order_id}/participants/{participant_id}/items/{order_item_id}]
+ Parameters
    + order_id: 1 (number) order's id
    + participant_id: 1 (number) user id
    + order_item_id: 1 (number) order item id

+ Request (application/json)
    + Attributes
        + options: [1, 2, 3] (required, array[number])

+ Response 200 (application/json)
    + Attributes (OrderItem)

### Delete a menu item [DELETE /orders/{order_id}/participants/{participant_id}/items/{order_item_id}]
+ Parameters
    + order_id: 1 (number) order's id
    + participant_id: 1 (number) user id
    + order_item_id: 1 (number) order item id

+ Response 204

## Users collection [/users]

### List All Users [GET]

+ Response 200 (application/json)
    + Attributes (array[User])

### Create a new User [POST]

+ Request (application/json)
    + Attributes
        + username: ekropotin (required, string) - user's login
        + password: ekropotinpassword (required, string) - user's password
        + role: EATER (required, UserRole)
        + full_name: Eugene (string) - user's name
        + email: testemail@gmail.com (string)
        + phone_number +71111111111 (string)

+ Response 201 (application/json)
    + Headers

            Location: /users/1

    + Attributes (User)

### Get an user [GET /users/{id}]
+ Parameters
    + id: 1 (number) user id

+ Response 200 (application/json)
    + Attributes (User)

### Update an User [PUT /users/{id}]
+ Parameters
    + id: 1 (number) user id

+ Request (application/json)
    + Attributes (User)

+ Response 200 (application/json)
    + Attributes (User)

### Delete an User [DELETE /users/{id}]
+ Parameters
    + id: 1 (number) user id

+ Response 204

### Update user's password [PUT /users/{id}/password]
+ Parameters
    + id: 1 (number) user id

+ Request (application/json)
    + Attributes
        + current_password: currpass (string) - current password
        + new_password: newpass (string) - new password
        + new_password_confirm: newpass (string) - new password once again

+ Response 204
