version: '2'

services:
  api:
    volumes:
      - ./app:/usr/src/app
    build: .
    ports:
      - "3000:3000"
    links:
      - mongodb
    entrypoint: npm start

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
