env:
  browser: false
  commonjs: true
  es6: true

extends: 'airbnb-base'

rules:
  comma-dangle:
    - off
  no-param-reassign:
    - off
  no-shadow:
    - off
  no-console:
    - off
  consistent-return:
    - off
  no-multi-assign:
    - off


